name: Build OpenCV Python Wheels

on:
  release:
    types: [published]

  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm]
        python-version: ["3.11", "3.12"]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update --allow-insecure-repositories
        sudo apt-get install --quiet -y --no-install-recommends \
          gstreamer1.0-gl \
          gstreamer1.0-opencv \
          gstreamer1.0-plugins-bad \
          gstreamer1.0-plugins-good \
          gstreamer1.0-plugins-ugly \
          gstreamer1.0-tools \
          libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-good1.0-dev \
          libgstreamer-plugins-bad1.0-dev \
          libgstreamer1.0-0 \
          libgstreamer1.0-dev \
          gstreamer1.0-plugins-base \
          gstreamer1.0-libav \
          libgbm-dev libdrm-dev \
          cmake wget curl

    - name: Run build script
      env:
        OPENCV_VER: "86"
        ENABLE_CONTRIB: "0"
        ENABLE_HEADLESS: "1"
        CMAKE_ARGS: "-DWITH_GSTREAMER=ON"
      run: |
        cd /tmp
        git clone git clone https://chromium.googlesource.com/chromiumos/platform/minigbm
        cd minigbm
        sudo cp *.h *.c /usr/include/
        sudo cp -R cros_gralloc external /usr/include/

        cd /tmp
        git clone https://git.codelinaro.org/clo/le/platform/vendor/qcom-opensource/gst-plugins-qti-oss.git -b imsdk.lnx.2.0.0.r1-rel
        cd /tmp/gst-plugins-qti-oss/gst-plugin-base
        mkdir build && cd build
        cmake .. -DGST_ALLOC_FOUND=1 -DGST_VIDEO_FOUND=1 -DGST_VERSION_REQUIRED=1.24.0 -DHAVE_DRV_H=0
        make -j$(nproc)
        sudo make install
        ninja -C build install
        cd /tmp/gst-plugins-qti-oss/gst-plugin-qmmfsrc
        mkdir build && cd build
        cmake .. -DGST_ALLOC_FOUND=1 -DGST_VIDEO_FOUND=1 -DGST_VERSION_REQUIRED=1.24.0 -DHAVE_DRV_H=0
        make -j$(nproc)
        sudo make install
        cd /tmp
        git clone --branch ${OPENCV_VER} --depth 1 --recurse-submodules --shallow-submodules https://github.com/opencv/opencv-python.git opencv-python-${OPENCV_VER}
        cd opencv-python-${OPENCV_VER}
        cp /home/runner/work/pyfiles/pyfiles/pyproject.toml .
        python -m pip wheel . --verbose

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: opencv_wheel_${{ matrix.os }}_py${{ matrix.python-version }}
        path: /tmp/opencv-python-*/opencv_python*.whl
        
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /tmp/opencv-python-*/opencv_python*.whl
